stages:
  - build

variables:
  DOCKER_DRIVER: overlay2

build_image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "Logging in to Docker Hub..."
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME"

    - echo "Building Docker image..."
    - docker build -t $DOCKERHUB_USERNAME/myapp:$CI_COMMIT_SHORT_SHA .

    - echo "Pushing Docker image..."
    - docker push $DOCKERHUB_USERNAME/myapp:$CI_COMMIT_SHORT_SHA

    # Save tag for next stage
    - echo "IMAGE_TAG=$CI_COMMIT_SHORT_SHA" >> build.env

  artifacts:
    reports:
      dotenv: build.env   # makes IMAGE_TAG available in next stage

