stages:
  - build

variables:
  # required for docker:dind non-TLS mode
  DOCKER_TLS_CERTDIR: ""
  # optional driver choice
  DOCKER_DRIVER: overlay2
  # ensure docker CLI talks to the service by hostname 'docker'
  DOCKER_HOST: tcp://docker:2375/

build_image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  # allow docker:dind to run properly
  privileged: true
  script:
    - echo "Logging in to Docker Hub..."
    # use --password-stdin so login works in non-interactive CI
    - echo "$DOCKERHUB_PASSWORD" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin

    - echo "Building Docker image..."
    - docker build -t "$DOCKERHUB_USERNAME/myapp:$CI_COMMIT_SHORT_SHA" .

    - echo "Pushing Docker image..."
    - docker push "$DOCKERHUB_USERNAME/myapp:$CI_COMMIT_SHORT_SHA"

    # Save tag for next stage (if you add more stages later)
    - echo "IMAGE_TAG=$CI_COMMIT_SHORT_SHA" >> build.env

  artifacts:
    reports:
      dotenv: build.env
